name: eco_simple_tasks
description: "Manage your tasks locally and simply."
publish_to: 'Ariel Ferrandin Morgan'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.39
  drift_flutter: ^0.2.7
  path: ^1.9.1
  path_provider: ^2.1.5
  easy_date_timeline: ^2.0.9
  intl: ^0.20.2
  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.3
  build_runner: ^2.8.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Gantari
      fonts:
        - asset: ./assets/fonts/Gantari-Regular.ttf
        - asset: ./assets/fonts/Gantari-Italic.ttf
          style: italic
        - asset: ./assets/fonts/Gantari-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

# Generate the code for the database with:
# flutter pub run build_runner clean
# flutter pub run build_runner build --delete-conflicting-outputs

